
print("Please enter a character for the eye")
eye = input()
print("\t----------")
print("\t- ",eye,"   ",eye,"-")
print("\t- -   -  -")
print("\t-  ---   -")
print("\t----------")
print("\t    #     ")
print("\t    #     ")
print("##################")
print("### ########## ###")
print("### ########## ###")
print("### ########## ###")
print("### ########## ###")
print("### ########## ###")